// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: acrechain/bridge/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgMintTokensToAccount struct {
	// sender specifies the account to receive the funds
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// to_address specifies the account to receive the funds
	ToAddress string `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// token amount
	Amounts github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amounts,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amounts"`
}

func (m *MsgMintTokensToAccount) Reset()         { *m = MsgMintTokensToAccount{} }
func (m *MsgMintTokensToAccount) String() string { return proto.CompactTextString(m) }
func (*MsgMintTokensToAccount) ProtoMessage()    {}
func (*MsgMintTokensToAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e966263b7e6cd1c, []int{0}
}
func (m *MsgMintTokensToAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintTokensToAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintTokensToAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintTokensToAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintTokensToAccount.Merge(m, src)
}
func (m *MsgMintTokensToAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintTokensToAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintTokensToAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintTokensToAccount proto.InternalMessageInfo

func (m *MsgMintTokensToAccount) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgMintTokensToAccount) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MsgMintTokensToAccount) GetAmounts() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amounts
	}
	return nil
}

type MsgMintTokensToAccountResponse struct {
}

func (m *MsgMintTokensToAccountResponse) Reset()         { *m = MsgMintTokensToAccountResponse{} }
func (m *MsgMintTokensToAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMintTokensToAccountResponse) ProtoMessage()    {}
func (*MsgMintTokensToAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e966263b7e6cd1c, []int{1}
}
func (m *MsgMintTokensToAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintTokensToAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintTokensToAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintTokensToAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintTokensToAccountResponse.Merge(m, src)
}
func (m *MsgMintTokensToAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintTokensToAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintTokensToAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintTokensToAccountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgMintTokensToAccount)(nil), "acrechain.bridge.MsgMintTokensToAccount")
	proto.RegisterType((*MsgMintTokensToAccountResponse)(nil), "acrechain.bridge.MsgMintTokensToAccountResponse")
}

func init() { proto.RegisterFile("acrechain/bridge/tx.proto", fileDescriptor_2e966263b7e6cd1c) }

var fileDescriptor_2e966263b7e6cd1c = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xbd, 0x8e, 0x13, 0x31,
	0x10, 0x5e, 0x5f, 0xd0, 0xa1, 0x33, 0x0d, 0x5a, 0xd0, 0x29, 0x17, 0x81, 0x13, 0xa5, 0x5a, 0x09,
	0x9d, 0x7d, 0x97, 0xeb, 0xe8, 0x12, 0x5a, 0x22, 0xa1, 0x28, 0x15, 0x4d, 0xe4, 0xf5, 0x5a, 0x8e,
	0x95, 0xac, 0x67, 0xb5, 0xe3, 0xa0, 0xd0, 0xf2, 0x04, 0x48, 0xbc, 0x00, 0x15, 0x05, 0x05, 0x4f,
	0xc0, 0x03, 0xa4, 0x8c, 0x44, 0x43, 0x05, 0x28, 0xa1, 0xe0, 0x31, 0xd0, 0xfe, 0x24, 0x8a, 0xd0,
	0x16, 0x54, 0x3b, 0x3b, 0xdf, 0xcc, 0x37, 0x9f, 0xbf, 0x8f, 0x5e, 0x49, 0x95, 0x6b, 0x35, 0x97,
	0xd6, 0x89, 0x38, 0xb7, 0x89, 0xd1, 0xc2, 0xaf, 0x79, 0x96, 0x83, 0x87, 0xf0, 0xe1, 0x11, 0xe2,
	0x15, 0xd4, 0x79, 0x62, 0x00, 0xcc, 0x52, 0x0b, 0x99, 0x59, 0x21, 0x9d, 0x03, 0x2f, 0xbd, 0x05,
	0x87, 0xd5, 0x7c, 0xe7, 0xb1, 0x01, 0x03, 0x65, 0x29, 0x8a, 0xaa, 0xee, 0x32, 0x05, 0x98, 0x02,
	0x8a, 0x58, 0xa2, 0x16, 0x6f, 0x6e, 0x63, 0xed, 0xe5, 0xad, 0x50, 0x60, 0x5d, 0x85, 0xf7, 0xbf,
	0x12, 0x7a, 0x39, 0x46, 0x33, 0xb6, 0xce, 0x4f, 0x61, 0xa1, 0x1d, 0x4e, 0x61, 0xa8, 0x14, 0xac,
	0x9c, 0x0f, 0x2f, 0xe9, 0x39, 0x6a, 0x97, 0xe8, 0xbc, 0x4d, 0x7a, 0x24, 0xba, 0x98, 0xd4, 0x7f,
	0xe1, 0x53, 0x4a, 0x3d, 0xcc, 0x64, 0x92, 0xe4, 0x1a, 0xb1, 0x7d, 0x56, 0x62, 0x17, 0x1e, 0x86,
	0x55, 0x23, 0xd4, 0xf4, 0xbe, 0x4c, 0x0b, 0x02, 0x6c, 0xb7, 0x7a, 0xad, 0xe8, 0xc1, 0xe0, 0x8a,
	0x57, 0x1a, 0x78, 0xa1, 0x81, 0xd7, 0x1a, 0xf8, 0x0b, 0xb0, 0x6e, 0x74, 0xb3, 0xf9, 0xd1, 0x0d,
	0x3e, 0xff, 0xec, 0x46, 0xc6, 0xfa, 0xf9, 0x2a, 0xe6, 0x0a, 0x52, 0x51, 0x0b, 0xae, 0x3e, 0xd7,
	0x98, 0x2c, 0x84, 0x7f, 0x9b, 0x69, 0x2c, 0x17, 0x70, 0x72, 0xe0, 0x7e, 0x7e, 0xef, 0xcf, 0xc7,
	0x6e, 0xd0, 0xef, 0x51, 0xd6, 0xac, 0x7e, 0xa2, 0x31, 0x03, 0x87, 0x7a, 0xf0, 0x85, 0xd0, 0xd6,
	0x18, 0x4d, 0xf8, 0x89, 0xd0, 0x47, 0x4d, 0xaf, 0x8c, 0xf8, 0xbf, 0x3e, 0xf3, 0x66, 0xc6, 0xce,
	0xcd, 0xff, 0x4e, 0x1e, 0x6e, 0xf7, 0xef, 0xde, 0x7d, 0xfb, 0xfd, 0xe1, 0xec, 0x3a, 0x7c, 0x26,
	0x1a, 0x62, 0x16, 0xa9, 0x75, 0x7e, 0xe6, 0xcb, 0xd5, 0x59, 0x61, 0x68, 0xb5, 0x3c, 0x7a, 0xb9,
	0xd9, 0x31, 0xb2, 0xdd, 0x31, 0xf2, 0x6b, 0xc7, 0xc8, 0xfb, 0x3d, 0x0b, 0xb6, 0x7b, 0x16, 0x7c,
	0xdf, 0xb3, 0xe0, 0xf5, 0xe0, 0xc4, 0xa5, 0x61, 0x2e, 0xe3, 0xa5, 0x7e, 0x55, 0x64, 0xa8, 0x60,
	0x79, 0xc2, 0xbf, 0x3e, 0x5e, 0x28, 0x5c, 0x8b, 0xcf, 0xcb, 0x98, 0xef, 0xfe, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xec, 0x13, 0xaa, 0xf5, 0x69, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	MintTokensToAccount(ctx context.Context, in *MsgMintTokensToAccount, opts ...grpc.CallOption) (*MsgMintTokensToAccountResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) MintTokensToAccount(ctx context.Context, in *MsgMintTokensToAccount, opts ...grpc.CallOption) (*MsgMintTokensToAccountResponse, error) {
	out := new(MsgMintTokensToAccountResponse)
	err := c.cc.Invoke(ctx, "/acrechain.bridge.Msg/MintTokensToAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	MintTokensToAccount(context.Context, *MsgMintTokensToAccount) (*MsgMintTokensToAccountResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) MintTokensToAccount(ctx context.Context, req *MsgMintTokensToAccount) (*MsgMintTokensToAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintTokensToAccount not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_MintTokensToAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintTokensToAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintTokensToAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acrechain.bridge.Msg/MintTokensToAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintTokensToAccount(ctx, req.(*MsgMintTokensToAccount))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acrechain.bridge.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintTokensToAccount",
			Handler:    _Msg_MintTokensToAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acrechain/bridge/tx.proto",
}

func (m *MsgMintTokensToAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintTokensToAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintTokensToAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amounts) > 0 {
		for iNdEx := len(m.Amounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMintTokensToAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintTokensToAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintTokensToAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgMintTokensToAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amounts) > 0 {
		for _, e := range m.Amounts {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgMintTokensToAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgMintTokensToAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintTokensToAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintTokensToAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amounts = append(m.Amounts, types.Coin{})
			if err := m.Amounts[len(m.Amounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMintTokensToAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintTokensToAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintTokensToAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
